services:
  accounts:
    image: "samilyleal/accounts:0.0.1-SNAPSHOT"
    container_name: accounts-ms
    ports:
      - "7474:7474"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ssl
  cards:
    image: "samilyleal/cards:0.0.1-SNAPSHOT"
    container_name: cards-ms
    ports:
      - "7484:7484"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ssl
  loans:
    image: "samilyleal/loans:0.0.1-SNAPSHOT"
    container_name: loans-ms
    ports:
      - "7494:7494"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ssl
networks:
  ssl:
    driver: "bridge"