spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related prod APIs!"
  contactDetails:
    name: "Octopus"
    email: "{cipher}afc9c3eb208c5a21a14cbc3719e7ce658ddd31602efb2db61f1376cb1d6b0f46072259d054e601aaa51d91bd7011b132"